### ISSUE TITLE
test: add test to check that all test files have a `beforeEach` statement

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#113]
With this new struct we are working on #64 , maybe this is a valid test to add? (and this check should run in PRs, because now there are more tiny steps a complete PR should have)

What do you think? @rrd108

**Comment by rrd108** [comment]
I am not sure about this.

You and me know what was this for, and why we need it :smile: 
Anyone else's code will go throught code review, so we can let them know. Human communication is better then a failing test IMHO.

Otherwise I can imagine that we will have tests like https://github.com/rrd108/vue-mess-detector/blob/main/src/index.test.ts where we do not need the `beforeEach` callback.

We can maybe add this to the contributor guide? 
Or refacot the code so we do not need to manually clean it if it is even possible.
