### ISSUE TITLE
use `apply` and `ignore` flags together

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#193]
It should error out

**Comment by David-Pena** [comment]
This is my fault so I'll asign it to myself. Unless you are doing it... @rrd108

**Comment by rrd108** [comment]
@David-Pena Why did ypu removed that error? I can't see the reason from the code, but I guessyou had a reason :smile:

**Comment by David-Pena** [comment]
> @David-Pena Why did you removed that error? I can't see the reason from the code, but I guessyou had a reason 😄

I was stuck receiving the error of both being applied when trying some changes of the new logic, I couldn't understand the hierarchy of the command line and config file, so I was kind of stuck with that. That's why I deleted for the moment to fix it at the end.

But then I realized that even without that check the logic is still working because of the `--apply`/`--ignore` grouping per rule/ruleset changes. So the real question is, is it really necessary that check? Meaning, is is really necessary to not allow apply and ignore?

Maybe adding some tests or finding edge-cases where the current logic without the check fails will helps us decide. But I'm all ears @rrd108 🙌

**Comment by rrd108** [comment]
> I was stuck receiving the error of both being applied when trying some changes of the new logic, I couldn't understand the hierarchy of the command line and config file, so I was kind of stuck with that. That's why I deleted for the moment to fix it at the end.

I see. My test was crappy that is why it passed. My bad.

The hierarchy is the following (maybe we should state it more clerly in the docs?)
1. The analízer has its own defaults (weekest)
2. If it finds a config file the values in it will overwrite the defaults
3. If the user provided some cli flags it will overwrite the previous ones. (strongest)

> But then I realized that even without that check the logic is still working because of the `--apply`/`--ignore` grouping per rule/ruleset changes. So the real question is, is it really necessary that check? Meaning, is is really necessary to not allow apply and ignore?

Using both `apply` and `ignore` will be confusing.

What is the expected behaviour of this?

```
yarn analyze -i=rrd,vue-strong -a=rrd
```

As the `ignore` flag states use *everything but* the ignored and `apply` means *only* the selected one(s) - it will end up check nothing.

I can imagine only one scenarion when using both can be useful, when I want to check one ruleset and ignore one rule from that ruleset.

What do you think?

**Comment by David-Pena** [comment]
I created a PR for this #198
