### ISSUE TITLE
add rule (vue-reccomended): Single-file component top-level element order

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#41]
https://vuejs.org/style-guide/rules-recommended.html#single-file-component-top-level-element-order

**Comment by David-Pena** [comment]
Would we assume the correct order for this is:
```
<script setup></script>
<template></template>
<style></style>
```

Or how could we approach this rule?

**Comment by rrd108** [comment]
Yes, choose the opiniated order above.

**Comment by David-Pena** [comment]
Hi @rrd108 I have a question, which interface / type should I use to handle all blocks? `script, template and style`?

![image](https://github.com/user-attachments/assets/8143452e-7700-41fd-a28f-02b691f01155)

I'm trying the `SFCBlock` type but I'm not sure here what to send as first parameter here:
![image](https://github.com/user-attachments/assets/bfee5f85-d5ce-4ff7-a626-8f2fb71a938b)

Because the `checkRules` function receives `SFCDescriptor`
![image](https://github.com/user-attachments/assets/e7c4cdf5-6b56-41d8-8fd0-614652abe7fa)

I think because of not using the correct struct, I'm having issues trying to test the rule with a project I have (the tests pass but with my own components doesnt report the rule)

**Comment by rrd108** [comment]
In `rulesCheck.ts` we execute all the checks. There you can see we use `script`, `template`, `styles` of `SFCDescriptor`, or the `SFCDescriptor` itself, according the need.

As here we want to check the order of the blocks, I guess `source` of `SFCDescriptor` is the one to use here.

Will it worj for this?

**Comment by David-Pena** [comment]
That was it! thanks
![image](https://github.com/user-attachments/assets/e26c5ace-c7aa-4525-a2d6-27eb0aa4c592)
