### ISSUE TITLE
componentFilenameCasing pages and layout for windows directory separator

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#56]

**Comment by David-Pena** [comment]
Hi @rrd108 

This issue is about the componentFilenameCasing shouldnt report error if the page / component is checking is `index.vue`?

**Comment by rrd108** [comment]
nuxt recommends kebab-case file names and not PascalCase like vue components.

So in this rule we have to detect if the project is nuxt or vue and report accordingly.

**Comment by David-Pena** [comment]
I'm wondering if the way to check if its a nuxt project would be by checking if there is a `nuxt.config`?

**Comment by rrd108** [comment]
Yep, I would do that.

**Comment by rrd108** [comment]
`componentFilenameCasing` already skip `pages` and `layouts` folders.

I can't remember where this issue came, but I guess it is not valid anymore.

**Comment by David-Pena** [comment]
This issue appear in my original discussion post, where I had a file `index.vue` and it reported that error and its because the method is handling regex for pascalCase and kebab-case but not checking when to use each one 

Discussion post: https://github.com/rrd108/vue-mess-detector/discussions/53
![image](https://github.com/user-attachments/assets/51a4125b-a581-4806-bf15-42c06eaad7bf)

Or maybe I understood it wrong since the beginning

**Comment by rrd108** [comment]
Can you plese check if the analyzer still report this file?

**Comment by David-Pena** [comment]
On it, give me a sec

**Comment by David-Pena** [comment]
Yes, its still reported:
![image](https://github.com/user-attachments/assets/045624c7-b59b-4d5f-87fb-aed94ffaf90f)

**Comment by rrd108** [comment]
Ok. I will add a failing test and a fix next week.

This weekend is our biggest tourist event, so I will not be around any code.
